### ISSUE TITLE
Unable to install in Laravel 6 & 7

### ISSUE THREAD

**Issue by nlivingstone** [TitasGailius/terminal#13]
Unable to use this package with Laravel 6 & 7 due to symfony/process version 5.0 being used.

Could be remedied by using symfony/process version 4.4.

Would be happy to create a pull request to remedy this.

**Comment by TitasGailius** [comment]
Laravel 7.x uses `"symfony/process": "^5.0"`.
Laravel 6.x uses  `"symfony/process": "^4.3.4"`.

Maybe Terminal could support both (v4 and v5) but before doing that I'd like to know what are the breaking changes and if any may impact the package.

**Comment by nlivingstone** [comment]
Symfony/process 4.4 -> 5.0 Changes.

- removed Process::inheritEnvironmentVariables()
- removed PhpProcess::setPhpBinary()
- Process must be instantiated with a command array, use Process::fromShellCommandline() when the command should be parsed by the shell
- removed Process::setCommandLine()

Looks like the only change that would affects the package is "Process::fromShellCommandline() must be instantiated with an array when command should be parsed by the shell". After reviewing the code and running the test suite everything appears to be working as expected. 

Am happy to add support for Laravel Version 5.5, would be hesitant to add support for Laravel Version 4.0 -> 5.5 as they have long since passed its EOL.

Let me know if I missed anything. Thanks for your patience.

**Comment by nlivingstone** [comment]
All tests passing when tested against symfony/process versions 4.3 - > 5.0

**Comment by TitasGailius** [comment]
Great
