### ISSUE TITLE
Possibility to add more Process wrapper functionality

### ISSUE THREAD

**Issue by defunctl** [TitasGailius/terminal#18]
Hey, thanks for the great tool!

I'm wonder if you'd be willing to expose setting the following functionality on the Symfony Process object via Terminal:

- [Process::setTty](https://github.com/symfony/process/blob/master/Process.php#L1040)
- [Process::setIdleTimeout](https://github.com/symfony/process/blob/master/Process.php#L1022)

**Comment by TitasGailius** [comment]
Hey,

Sure thing, I add it to the backlog.
In the meantime, you can achieve the same result with something like this:

```php
$process = Terminal::command(...)->process();

$process->setTty(...);
$process->setIdleTimeout(...);

Terminal::runProcess($process);
```

**Comment by defunctl** [comment]
That's exactly what I'm doing now, would just be cleaner to have it right in the builder. Certainly a "nice to have" of course.

Thanks a lot, Titas!

**Comment by TitasGailius** [comment]
Added to 4.0.0 release. 

https://github.com/TitasGailius/terminal/releases/tag/0.4.0
