### ISSUE TITLE
Unable to mock Symfony Process with TTY enabled.

### ISSUE THREAD

**Issue by luisaveiro** [TitasGailius/terminal#19]
#### Description
I'm trying to mock the underlying Symfony's Process that has setTty enabled. However the test is failing since Terminal is executing psysh debugger.

Below is example code
```php
$process = Mockery::mock(Process::class)
    ->shouldReceive('run')
    ->once()
    ->andReturn(true);

Terminal::fake([
    'php ./vendor/psy/psysh/bin/psysh' => Terminal::response($process),
]);

Terminal::command('php ./vendor/psy/psysh/bin/psysh')
    ->process()
    ->setTty(Process::isTtySupported())
    ->run();

Terminal::assertExecuted('php ./vendor/psy/psysh/bin/psysh');
```

#### Current Behaviour
When I run PHPUnit the following happens.

<img width="573" alt="Screenshot 2020-06-25 at 20 41 14" src="https://user-images.githubusercontent.com/758559/85788031-3985d800-b724-11ea-95db-444bf279b09a.png">

When I type "exit" to leave psysh debugger. The test fails

<img width="728" alt="Screenshot 2020-06-25 at 20 42 26" src="https://user-images.githubusercontent.com/758559/85788131-62a66880-b724-11ea-9f46-1800aab50cf7.png">

#### Expected Behaviour
I'm expecting `Terminal:fake()` would not execute the command regardless if TTY enabled.

**Comment by TitasGailius** [comment]
`Terminal::process()` method returns an actual Symfony process instance which is not mocked.

You may solve this issue by setting TTY and running the script using Terminal:

```php
Terminal::fake([
    'php ./vendor/psy/psysh/bin/psysh' => Terminal::response($process),
]);

Terminal::command('php ./vendor/psy/psysh/bin/psysh')
    ->tty(Process::isTtySupported())
    ->run();

Terminal::assertExecuted('php ./vendor/psy/psysh/bin/psysh');
```

You may access the underlying Symfony process instance but run it using Terminal like this:

```php
$process = Terminal::command('php ./vendor/psy/psysh/bin/psysh')->process();

$process->setTty(Process::isTtySupported());

Terminal::runProcess($process);
```

**Comment by luisaveiro** [comment]
@TitasGailius thank you for your suggestions. I have made the changes in my code and my tests pass. Thank you for helping.
