### ISSUE TITLE
this is not working on windows

### ISSUE THREAD

**Issue by AhsanAbrar** [TitasGailius/terminal#21]
Windows 10

```php
    $response = Terminal::run('ls');

    print_r( $response->lines() );
```

here is the output:

```
array:1 [▼
  0 => TitasGailius\Terminal\OutputLine {#288 ▼
    #type: "err"
    #line: """
      'ls' is not recognized as an internal or external command,
      operable program or batch file.
      """
  }
]
```

any idea why i'm getting this error?

**Comment by TitasGailius** [comment]
It's working just fine. `ls` is Unix command. If you run this command in Command Prompt on Windows, you would get the exact same message.

**Comment by shadoWalker89** [comment]
What @TitasGailius said, the equivalent for windows is `dir`

**Comment by AhsanAbrar** [comment]
Actually, symfony 5 process not working on windows.

```bash
php -v
```

```bash
composer -v
```

these commands working fine with windows cmd but not with symfony 5 process.
