### ISSUE TITLE
Can't get response code

### ISSUE THREAD

**Issue by aerni** [TitasGailius/terminal#26]
First, thanks for this awesome package! I found that the documented `$response->code()` method doesn't work.

**Code:**
```php
$response = Terminal::run('ls');
$response->code();
```

**Error:**
```
call_user_func() expects parameter 1 to be a valid callback, class 'Symfony\Component\Process\Process' does not have a method 'code'
```

**Comment by code2prog** [comment]
@aerni php8?

**Comment by aerni** [comment]
No. PHP 7.4.

**Comment by TitasGailius** [comment]
There was a mistake in the documentation. Please use `$response->getExitCode()`.

I'd accept a PR with a `code` method in a `Response` class that would simply be a syntactic sugar around `getExitCode`.
