### ISSUE TITLE
PHP 8 Compatibility - required parameter follows optional parameter

### ISSUE THREAD

**Issue by morrislaptop** [TitasGailius/terminal#29]
Following from #27 

https://php.watch/versions/8.0/deprecate-required-param-after-optional

Might not get picked up in tests which disable deprecated warnings?

**Comment by TitasGailius** [comment]
Thank you for reporting the issue.

Fixed and tagged as `1.0.1`: https://github.com/TitasGailius/terminal/releases/tag/1.0.1
