### ISSUE TITLE
Faking commands passed as array is not possible

### ISSUE THREAD

**Issue by paneidos** [TitasGailius/terminal#8]
A command passed as array is impossible to fake, because arrays aren't valid array keys.

E.g.:
```
Terminal::fake(["id '-u'" => '1000']);
Terminal::run(['id', '-u']); // Raises warning: 'Illegal offset type'
```

**Comment by TitasGailius** [comment]
Can confirm. Do you mind opening a PR to fix this?

**Comment by TitasGailius** [comment]
nvm, here's the PR https://github.com/TitasGailius/terminal/pull/9 I just need to think if it's the right way to go about it before merging.
